// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  // `prisma migrate` needs a direct (non-pgbouncer) connection to run DDL;
  // the app itself connects through the pooled DATABASE_URL instead (see
  // src/lib/prisma.js), since transaction-mode pgbouncer doesn't support
  // prepared statements/DDL reliably.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
